title: "Playwright 101 Workshop"
description: "From User Stories to Automated Tests with Playwright, GitHub Copilot & Azure DevOps"
remote_theme: just-the-docs/just-the-docs
baseurl: ""
url: "https://vigilant-succotash-8wgy34z.pages.github.io"
exclude:
  - playwright-tests/
  - delivery/
  - node_modules/
  - package.json
  - package-lock.json
  - Gemfile.lock
  - assets/initial-research.md
defaults:
  - scope:
      path: "images"
    values:
      nav_exclude: true
heading_anchors: true
